/*
 * productinfo.h
 *
 * Disp device info!
 *
 * Copyright (C) HMCT Corporation 2013
 *
 */
#ifndef  _PRODUCTINFO_H_
#define _PRODUCTINFO_H_
enum {
PRODUCTINFO_VENDOR_ID,
PRODUCTINFO_BOARD_ID,
PRODUCTINFO_HW_VERSION_ID,
PRODUCTINFO_LCD_ID,
PRODUCTINFO_CTP_ID,
PRODUCTINFO_HDMI_ID,
PRODUCTINFO_MAIN_CAMERA_ID,
PRODUCTINFO_FRONT_CAMERA_ID,
PRODUCTINFO_DDR_ID,
PRODUCTINFO_EMMC_NAND_ID,
PRODUCTINFO_NAND_ID,
PRODUCTINFO_SENSOR_ACCELEROMETER_ID,
PRODUCTINFO_SENSOR_COMPASS_ID,
PRODUCTINFO_SENSOR_ALPS_ID,
PRODUCTINFO_BT_ID,
PRODUCTINFO_WIFI_ID,
PRODUCTINFO_CODEC_ID,
PRODUCTINFO_MODEM_ID,
PRODUCTINFO_LED_ID,
// Please add it, yourself!
PRODUCTINFO_MAX_ID = 40,
PRODUCTINFO_SIGN = 0x7fffffff,
};
int productinfo_register(int id, const char *devicename, const char *deviceinfo);
#endif
